clean:
	rm -rf *.dSYM *.exe *~

inter-1605: inter-1605.cpp
	g++ -Wall -DDEBUG -g inter-1605.cpp -o inter-1605.exe

inter-1606: inter-1606.cpp
	g++ -Wall -DDEBUG -std=c++11 -g inter-1606.cpp -o inter-1606.exe
