clean:
	rm -rf *.dSYM *.exe *~

inter-1605: inter-1605.cpp
	g++ -Wall -DDEBUG -g inter-1605.cpp -o inter-1605.exe

inter-1606: inter-1606.cpp
	g++ -Wall -DDEBUG -std=c++11 -g inter-1606.cpp -o inter-1606.exe

198-a: 198-a.cpp
	g++ -Wall -DDEBUG -std=c++11 -g 198-a.cpp -o 198-a.exe

5465: 5465.cpp
	g++ -Wall -DDEBUG -std=c++11 -g 5465.cpp -o 5465.exe

60-view-cn: 60-view-cn.cpp
	g++ -Wall -DDEBUG -g 60-view-cn.cpp -o 60-view-cn.exe && ./60-view-cn.exe

4-view-cn: 4-view-cn.cpp
	g++ -Wall -std=c++11 -DDEBUG -g 4-view-cn.cpp -o 4-view-cn.exe && ./4-view-cn.exe
