#!/usr/bin/env bash

if [[ $(uname) = "Darwin" ]]; then
    CC=g++-11
else
    CC=g++
fi

if [ $1 = "clean" ]; then
    rm -rf *.exe *.dSYM
else
    bname="${1%.*}"
    src=${bname}.cpp
    target=${bname}.exe

    # -fsanitize=address -ftrapv
    $CC -Wall -std=c++11 -D_DEBUG -Wno-unused-const-variable -ftrapv $src -o ${target}
    if [ -e $target ]; then
      ./$target
    fi
fi
