clean:
	rm -rf *.exe *~ *.dSYM

3250: 3250.cpp
	g++ -Wall -DDEBUG -std=c++98 -g 3250.cpp -o 3250.exe && ./3250.exe

2559: 2559.cpp
	g++ -Wall -DDEBUG -std=c++98 -g 2559.cpp -o 2559.exe && ./2559.exe

3494: 3494.cpp
	g++ -Wall -DDEBUG -std=c++98 -g 3494.cpp -o 3494.exe && ./3494.exe

2796: 2796.cpp
	g++ -Wall -DDEBUG -std=c++98 -g 2796.cpp -o 2796.exe && ./2796.exe
