clean:
	rm -rf *.dSYM *.exe *~

1258: 1258.cpp
	g++ -Wall -DDEBUG -g 1258.cpp -o 1258.exe && ./1258.exe

1259: 1259.cpp
	g++ -Wall -DDEBUG -g 1259.cpp -o 1259.exe && ./1259.exe

1260: 1260.cpp
	g++ -Wall -DDEBUG -g 1260.cpp -o 1260.exe && ./1260.exe

1261: 1261.cpp
	g++ -Wall -DDEBUG -g 1261.cpp -o 1261.exe && ./1261.exe
