clean:
	rm -rf *.dSYM *.exe *~

1329: 1329.cpp
	g++ -Wall -DDEBUG -g 1329.cpp -o 1329.exe && ./1329.exe

1330: 1330.cpp
	g++ -Wall -DDEBUG -g 1330.cpp -o 1330.exe && ./1330.exe

1248: 1248.cpp
	g++ -Wall -DDEBUG -g 1248.cpp -o 1248.exe && ./1248.exe
