clean:
	rm -rf *.dSYM *.exe *~

a: a.cpp
	g++ -Wall -DDEBUG -g a.cpp -o a.exe && ./a.exe

b: b.cpp
	g++ -Wall -DDEBUG -g b.cpp -o b.exe && ./b.exe

c: c.cpp
	g++ -Wall -DDEBUG -g c.cpp -o c.exe && ./c.exe

e: e.cpp
	g++ -Wall -DDEBUG -g e.cpp -o e.exe && ./e.exe
