clean:
	rm -rf *.dSYM *.exe *~

1328: 1328.cpp
	g++ -Wall -DDEBUG -g 1328.cpp -o 1328.exe && ./1328.exe

1326: 1326.cpp
	g++ -Wall -DDEBUG -g 1326.cpp -o 1326.exe && ./1326.exe

1238: 1238.cpp
	g++ -Wall -DDEBUG -g 1238.cpp -o 1238.exe && ./1238.exe

1237: 1237.cpp
	g++ -Wall -DDEBUG -g 1237.cpp -o 1237.exe && ./1237.exe
