clean:
	rm -rf *.dSYM *.exe *~

uva1626: uva1626.cpp
	g++ -Wall -DDEBUG -g uva1626.cpp -o uva1626.exe

poj1191: poj1191.cpp
	g++ -Wall -DDEBUG -g poj1191.cpp -o poj1191.exe

poj1191_1: poj1191_1.cpp
	g++ -Wall -DDEBUG -g poj1191_1.cpp -o poj1191_1.exe

sdutoj1546: sdutoj1546.cpp
	g++ -Wall -DDEBUG -g sdutoj1546.cpp -o sdutoj1546.exe

sdutoj1546_1: sdutoj1546_1.cpp
	g++ -Wall -DDEBUG -g sdutoj1546_1.cpp -o sdutoj1546_1.exe

uva1291: uva1291.cpp
	g++ -Wall -DDEBUG -std=c++11 -g uva1291.cpp -o uva1291.exe

luogu5760: luogu5760.cpp
	g++ -Wall -DDEBUG -std=c++11 -g luogu5760.cpp -o luogu5760.exe

c_literal:
	gcc -Wall c_literal.c -o c_literal.exe
