clean:
	rm -rf *.dSYM *.exe *~

uva1626: uva1626.cpp
	g++ -Wall -DDEBUG -g uva1626.cpp -o uva1626.exe

poj1191: poj1191.cpp
	g++ -Wall -DDEBUG -g poj1191.cpp -o poj1191.exe

poj1191_1: poj1191_1.cpp
	g++ -Wall -DDEBUG -g poj1191_1.cpp -o poj1191_1.exe

sdoj1546: sdoj1546.cpp
	g++ -Wall -DDEBUG -g sdoj1546.cpp -o sdoj1546.exe

sdoj1546_1: sdoj1546_1.cpp
	g++ -Wall -DDEBUG -g sdoj1546_1.cpp -o sdoj1546_1.exe
