clean:
	rm -rf *.dSYM *.exe *~

uva1626: uva1626.cpp
	g++ -Wall -DDEBUG -g uva1626.cpp -o uva1626.exe

poj1191: poj1191.cpp
	g++ -Wall -DDEBUG -g poj1191.cpp -o poj1191.exe

poj1191_1: poj1191_1.cpp
	g++ -Wall -DDEBUG -g poj1191_1.cpp -o poj1191_1.exe
